config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  devise_scope :user do
    get 'register' => 'registrations#new', as: :new_user_registration
    get 'profile' => 'registrations#edit', as: :edit_user_registration
  end

  devise_for :users, path: '', only: [:sessions]
  devise_for :users, skip: [:sessions],
             controllers: {registrations: 'registrations'},
             path_names: { sign_up: 'register', edit: 'profile'}

  resources :users, only: [:index, :show], :concerns => :paginatable do
    member do
      get 'subscriptions(/page/:page)', action: :subscriptions, as: :subscriptions
      get 'subscribers(/page/:page)', action: :subscribers, as: :subscribers
    end
  end

  resources :posts, only: [:index, :new, :create, :destroy]
  resources :subscriptions, only: [:create, :destroy]

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end
  root  'pages#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  #TODO: Try to change ordering to 'created_at DESC'
  default_scope -> { order('id DESC') }

  validates :text, presence: true,
            length: { minimum: 1, maximum: 140 }

  @@per_page = 10
  def self.per_page
    @@per_page
  end

  def self.page(start_id = nil)
    posts = limit(Post.per_page)
    posts = posts.where('posts.id < ?', start_id) if start_id

    have_more = ids.last < posts.last.id if posts.any?

    [posts, have_more]
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :subscribed_to, :class_name => 'User'

  validates :user_id, presence: true
  validates :subscribed_to_id, presence: true
  validates :subscribed_to_id, uniqueness: { scope: :user_id, message: 'Unable to subscribe twice to one user' }
  validate :self_subscription

  private

  def self_subscription
    errors.add(:subscribed_to_id, 'Unable to subscribe to yourself.') if user_id == subscribed_to_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  default_scope -> { order(:id) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  has_many :posts, dependent: :destroy

  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_to, through: :subscriptions

  has_many :inverse_subscriptions, class_name: 'Subscription', foreign_key: 'subscribed_to_id', dependent: :destroy
  has_many :subscribers, through: :inverse_subscriptions, source: :user

  def feed
    Post.where(user_id: subscribed_to.ids << id)
  end

  def subscribed_to?(user)
    subscriptions.exists?(subscribed_to_id: user.id) if user
  end

  def subscribe(user)
    subscriptions.build(subscribed_to_id: user.id).save if user
  end

  def unsubscribe(user)
    subscriptions.find_by(subscribed_to_id: user.id).destroy if user and subscribed_to?(user)
  end

  # Don't allow to change email w/o password
  def update_without_password(params, *options)
    params.delete(:email)
    super(params, *options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  after_filter :xhr_flash_discard

  rescue_from ActionController::InvalidAuthenticityToken, with: :redirect_to_login

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :avatar << :avatar_cache << :remove_avatar
  end

  def xhr_flash_discard
    return unless request.xhr?
    flash.discard  # don't want the flash to appear when you reload page
  end

  def redirect_to_login
    if not user_signed_in?
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
        format.js { render js: "window.location = '#{new_user_session_path}'" }
      end
      return false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @body_class = 'body-index'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  # Current user's feed (subscriptions + own posts)
  def index
    @user = current_user

    @posts, @show_more = @user.feed.page params[:last]

    @post = Post.new if not request.xhr?

    render template: 'users/show'
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post was successfully created.'
      else
        flash[:alert] = 'Post was not created.'
      end

      format.html { redirect_to posts_path}
      format.js   {}
    end
  end

  def destroy
    @post = Post.find(params[:id])

    respond_to do |format|
      flash[:notice] =
      if @post.destroy
        'Post was successfully deleted.'
      else
        'Post was not deleted.'
      end

      format.html { redirect_to posts_path}
      format.js   {}
    end
  end

  private
    def post_params
      params.require(:post).permit(:text)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do |user|
      verify_recaptcha(model: user, message: 'There was an error with the recaptcha code below. Please re-enter the code.')
      flash.delete :recaptcha_error
    end
  end

  def update_resource(user, params)
    if user.email == params[:email] and params[:password].blank?
      params.delete(:current_password)
      user.update_without_password(params)
    else
      user.update_with_password(params)
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!

  #TODO: handle errors

  def create
    @user = User.find(params[:id])

    flash[:notice] =
    if current_user.subscribe(@user)
      "Successfully subscribed to #{@user.email}."
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js   {}
    end
  end

  def destroy
    @user = User.find(params[:id])

    flash[:notice] =
    if current_user.unsubscribe(@user)
        "Successfully unsubscribed from #{@user.email}."
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js   {}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # List of users
  def index
    @users = User.page params[:page]
  end

  # User's own posts only
  def show
    @user = User.find(params[:id])

    @posts, @show_more = @user.posts.page params[:last]

    @post = @user.posts.build if not request.xhr? and @user == current_user
  end

  def subscribers
    @title = 'subscribers'
    @user = User.find params[:id]
    @users = @user.subscribers.page(params[:page]).per(36)
    render 'users_grid'
  end

  def subscriptions
    @title = 'subscriptions'
    @user = User.find params[:id]
    @users = @user.subscribed_to.page(params[:page]).per(36)
    render 'users_grid'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_simple_pagination.html.slim
.clearfix
i == (page_entries_info entries, entry_name: entry_name.singularize).capitalize
nav
  ul.pager
    li.previous == link_to_previous_page entries, 'Prev', remote: remote
    li.next == link_to_next_page entries, 'Next', remote: remote

app/views/layouts/_errors.html.slim
- if errors.any?
  .alert.alert-dismissible.alert-danger
    button.close[type="button" data-dismiss="alert"]
      span[aria-hidden="true"] ×
      span.sr-only Close
    - errors.each do |text|
      - if text.is_a?(String)
      = text
      br

app/views/layouts/_errors.js.erb
$("#messages").append("<%= escape_javascript(render :partial => 'layouts/errors.html', locals: {errors: errors}).html_safe %>");

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - alert_class = "alert-#{name.to_s == 'alert' ? 'danger' : 'info'}"
    .alert.alert-dismissible[class=alert_class role="alert"]
      button.close[type="button" data-dismiss="alert"]
        span[aria-hidden="true"] ×
        span.sr-only Close
      = msg

app/views/layouts/_navigation.html.slim
= navbar static: :top do
  = navbar_header brand: "#{image_tag('logo.png')}Switter", brand_link: root_url
  = navbar_collapse do
    = navbar_group id: 'menu' do
      = navbar_item 'Feed', posts_path
      = navbar_item 'Users', users_path
    == render '/layouts/user_menu'

app/views/layouts/_user_menu.html.slim
= navbar_group id: 'user-menu', align: 'right' do
  - if user_signed_in?
    = navbar_item edit_user_registration_path, id: 'navbar-profile' do
      - if current_user.avatar.thumb.url.present?
        = image_tag current_user.avatar.thumb.url, class: 'img-rounded'
      = current_user.email
    = navbar_item 'Sign Out', destroy_user_session_path, {}, {:'data-method' => :delete}
  - else
    = navbar_item 'Register', new_user_registration_path, {}, {'data-no-turbolink' => true}
    = navbar_item 'Sign In', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title = content_for?(:title) ? yield(:title) : 'Switter'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Switter'}"
    = favicon_link_tag '/favicon.png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body[class=@body_class]
    header
      == render 'layouts/navigation'
    .container
      main[role="main"]
        #messages
          == render 'layouts/messages'
        #content
          == yield :content if content_for? :content
          == yield

app/views/layouts/application.js.erb
$("#messages").html("<%= escape_javascript(render :partial => 'layouts/messages').html_safe %>");
<%= yield %>

app/views/layouts/panel.html.slim
- content_for :content, flush: true do
  .row
    - @panel_col_class ||= 'col-sm-6 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4'
    div[class=@panel_col_class]
      .panel.panel-default
        .panel-heading
          == yield :panel_heading
        .panel-body
          == yield :panel_body
        .panel-footer
          == yield :panel_footer
== render  template: "layouts/application"

app/views/pages/index.html.slim
#switter
  = image_tag 'switter.png'
  .clearfix
  .links
    h1 simple #{link_to 'twitter', 'https://www.twitter.com'} clone
    br
    = link_to 'Join now!', new_user_registration_path, class: 'btn btn-lg btn-primary btn-block'

app/views/posts/_form.html.slim
h1 New post
= form_for @post, remote: true do |f|
  - if @post.errors.any?
    #error_explanation
      h2
        = pluralize(@post.errors.count, 'error')
        |  prohibited this article from being saved:
      ul
        - @post.errors.full_messages.each do |msg|
          li
            = msg
  .form-group
    = f.label :text
    '
    i
      | (
      span#counter
        | 140
      | )
    = f.text_area :text, class: 'form-control', id: 'post-input'
  .form-group
    = f.submit class: 'btn btn-lg btn-primary', id: 'post-submit', disabled: true

app/views/posts/_post.html.slim
- unless post.new_record?
  div[id="p#{post.id}"]
    div
      span.glyphicon.glyphicon-user
      i
        - if post.user == current_user
          | You
        - else
          = link_to post.user.email, post.user
        | :
      - if post.user == current_user
        .delete-post.pull-right[data-toggle="tooltip" data-placement="top" data-title="Delete this post"]
          = link_to post_path(post), method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
            span.glyphicon.glyphicon-remove

      i.pull-right[data-toggle="tooltip" data-placement="top" data-title="#{post.created_at}"]
        = "#{time_ago_in_words(post.created_at)} ago"
    .well
      = post.text

app/views/posts/create.js.erb
<% if @post.errors.any? -%>
<%= render :partial => 'layouts/errors', locals: {errors: @post.errors.full_messages} -%>
<% else -%>
$("<%= escape_javascript(render @post) %>").prependTo("#posts");
$('#post-form form')[0].reset();
<% end %>

app/views/posts/destroy.js.erb
<% if @post.errors.any? -%>
<%= render :partial => 'layouts/errors', locals: {errors: @post.errors.full_messages} -%>
<% else -%>
$("#p<%= @post.id %>").remove();
<% end %>

app/views/subscriptions/_button.html.slim
- if user_signed_in?
  - if user and user != current_user
    span[id="s#{user.id}-button"]
      - if current_user.subscribed_to?(user)
        = render 'subscriptions/unsubscribe_link', user: user
      - else
        = render 'subscriptions/subscribe_link', user: user

app/views/subscriptions/_button.js.erb
$("#s<%= user.id %>-button").html('<%= render "subscriptions/#{new_action}_link", user: user %>');
$("#s<%= user.id %>-count").html('<%=  user.subscribers.count %>');

app/views/subscriptions/_subscribe_link.html.slim
= link_to 'Subscribe', subscriptions_path(id: user), method: :post, remote: true, class: 'btn btn-info'

app/views/subscriptions/_unsubscribe_link.html.slim
= link_to 'Unsubscribe', subscription_path(id: user), method: :delete, remote: true, class: 'btn btn-warning'

app/views/subscriptions/create.js.erb
<%= render 'button', new_action: 'unsubscribe', user: @user %>

app/views/subscriptions/destroy.js.erb
<%= render 'button', new_action: 'subscribe', user: @user %>

app/views/users/_user.html.slim
.avatar-thumb[data-toggle="tooltip" data-placement="top auto" data-title="#{user.email}"]
  = link_to user do
    = image_tag user.avatar.thumb.url if user.avatar.thumb.url.present?

app/views/users/_user_card.html.slim
.pull-left
  .avatar
    = image_tag user.avatar.url if user.avatar.url.present?
.pull-left
  h3
    = user.email
    '
    = render partial: 'subscriptions/button', locals: {user: user}
  p
    = link_to subscribers_user_path(user), remote: true,
              data: {toggle: 'popover', placement: 'right', html: true },
              class: 'dotted', id: 'subscribers' do
      span.label.label-default[id="s#{user.id}-count"]
        = user.subscribers.count
      '
      span
        | Subscribers
  p
    = link_to subscriptions_user_path(user), remote: true,
              data: {toggle: 'popover', placement: 'right', html: true },
              class: 'dotted', id: 'subscriptions' do
      span.label.label-default
        = user.subscribed_to.count
      '
      span
        | Subscriptions
.clearfix

app/views/users/index.html.slim
h1 Users
- @users.each do |user|
  h4
    = link_to user do
      = image_tag user.avatar.thumb.url, class: 'img-rounded' if user.avatar.thumb.url.present?
      '
      = user.email
    '
    = render partial: 'subscriptions/button', locals: {user: user}
.center
  == paginate @users

app/views/users/show.html.slim
== render 'users/user_card', user: @user
- if @post
  #post-form
    == render partial: 'posts/form'
#posts
  == render @posts

- if @show_more
  .center
    = link_to 'Show more', url_for(last: @posts.last.id), remote: true, data: {disable_with: 'Loading...'},
              id: 'show-more', class: 'btn btn-lg btn-primary'

app/views/users/show.js.erb
<% if @posts.any? -%>
$("<%= escape_javascript(render @posts) %>").appendTo("#posts");
<% end %>

<% if @show_more -%>
$("#show-more").attr("href", "<%= url_for(last: @posts.last.id) %>");
<% else -%>
$("#show-more").remove();
<% end %>

app/views/users/users_grid.html.slim
.page-header
  h1
    = @user.email
    '
    small = @title
== render @users
.clearfix
== paginate @users

app/views/users/users_grid.js.erb
$("#<%= @title%>").data('bs.popover').setContent("<%= escape_javascript("
#{render @users}
#{render 'common/simple_pagination', entries: @users, entry_name: @title, remote: true}
").html_safe %>");